apiVersion: v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLables:
      - label
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-env
        image: phidp/nodejs-demo-app:1.0
        env:
        - name: MONGO_USERNAME
          value: "admin"
        - name: MONGO_PASSWORD
          value: "123456a@"
        - name: MONGO_HOSTNAME
          value: "db"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB
          value: sharkinfo
