apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-env
        image: phidp/nodejs-demo-app:1.1
        envFrom:
          - configMapRef:
              name: mongo-config
          - secretRef:
              name: mongo-secret
        # env:
        # - name: MONGO_USERNAME
        #   value: "admin"
        # - name: MONGO_PASSWORD
        #   value: "123456a@"
        # - name: MONGO_HOSTNAME
        #   value: "db"
        # - name: MONGO_PORT
        #   value: "27017"
        # - name: MONGO_DB
        #   value: sharkinfo
        ports:
        - name: container-port
          containerPort: 8080
        # resources:
        #   requests:
        #     memory: 128Mi
        #     cpu: 256Mi
        #   limits:
        #     memory: 1Gi
        #     cpu: 1Gi


