apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
  - name: nodejs-svc
    nodePort: 30007
    port: 8080
    targetPort: container-port